[workspace]
members = [
    "codegen",
    "codegen-bin",
    # "bizir"
]
default-members = [
    "codegen-bin"
]

# [[bin]]
# name = "generate"
# path = "codegen-bin/src/main.rs"
# name = "bizir"
# path = "bizir/src/main.rs"
